server:
  port: 8082

security:
  oauth2:
    client:
      clientId: firstapp1599109189098
      clientSecret: 62f41ea9224bde26b0d16ca8a78d9e4d7a41d3853577e12765b48d1781077109
      accessTokenUri: http://10.113.97.165:8081/api/oauth/token
      userAuthorizationUri: http://10.113.97.165:8081/api/oauth/authorize
    resource:
      userInfoUri: http://10.113.97.165:8081/api/principal

spring:
  thymeleaf:
    cache: false

