server:
  port: 8082
  #forwardHeadersStrategy: NATIVE

security:
  oauth2:
    client:
      clientId: q
      clientSecret: w
      accessTokenUri: http://localhost:8081/api/oauth/token
      userAuthorizationUri: http://localhost:8081/api/oauth/authorize
      #preEstablishedRedirectUri: http://localhost:8082/userInfo
      use-current-uri: false
    resource:
      userInfoUri: http://localhost:8081/api/principal

spring:
  thymeleaf:
    cache: false

