server:
  port: 8082

security:
  oauth2:
    client:
      clientId: q
      clientSecret: w
      accessTokenUri: http://localhost:8081/api/oauth/token
      userAuthorizationUri: http://localhost:8081/api/oauth/authorize
      #redirectUri: http://localhost:8082/login
      #use-current-uri: false
    resource:
      userInfoUri: http://localhost:8081/api/principal

spring:
  thymeleaf:
    cache: false

