# Parameters required by OHauth2(Oauth2) API

server:
  port: 8082

security:
  oauth2:
    client:
      clientId: q
      clientSecret: w
      accessTokenUri: http://10.113.97.165:8081/api/oauth/token
      userAuthorizationUri: http://10.113.97.165:8081/api/oauth/authorize
      #redirectUri: http://localhost:8082/login
      #use-current-uri: false
    resource:
      userInfoUri: http://10.113.97.165:8081/api/principal

spring:
  thymeleaf:
    cache: false

