server:
  port: 8082

security:
  oauth2:
    client:
      clientId: ababa1599132186874
      clientSecret: 6be304f73cd8aeae4eead1780f607525ace3e03e5c45bf5d2b617f6eb8504905
      accessTokenUri: http://localhost:8081/api/oauth/token
      userAuthorizationUri: http://localhost:8081/api/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/api/principal

spring:
  thymeleaf:
    cache: false

